### ISSUE TITLE
Year in @inproceedings entries

### ISSUE THREAD

**Issue by russella** [marcodaniel/trad-biblatex#18]
Dear Marco, Thanks again for your great work on this project. I have begun to incorporate your code into the LaTeX base for the journal Theory of Computing. A few minor things have come up.

It seems that the year isn't in the right place for @inproceedings entries. (It IS in the right place for incollection, by the way, which has the same rules in the plain.) Consider the entry:

@inproceedings{DBLP:conf/soda/AingworthCM96,
  author    = {Donald Aingworth and
               Chandra Chekuri and
               Rajeev Motwani},
  title     = {Fast Estimation of Diameter and Shortest Paths (without
               Matrix Multiplication)},
  pages     = {547--553},
  doi       = {10.1145/313852.314117},
  crossref  = {DBLP:conf/soda/1996},
}

@proceedings{DBLP:conf/soda/1996,
  editor    = {{\'E}va Tardos},
  booktitle     = {Proceedings of the Seventh Annual ACM-SIAM Symposium on
               Discrete Algorithms},
  publisher = {ACM/SIAM},
  year      = {1996},
}

Then plain with BibTeX produces the output 
![bibtex-inproceedings](https://f.cloud.github.com/assets/2408045/971409/e818e3b8-05e6-11e3-86a7-32aa33dea496.png)
whereas Biblatex with trad-plain produces
![biblatex-inproceedings](https://f.cloud.github.com/assets/2408045/971411/f4541eae-05e6-11e3-980e-a565f62788c0.png)

**Comment by marcodaniel** [comment]
Fixed now by modifying the bibmacro `inproc:crossref:extra`
