### ISSUE TITLE
Techreport number & parentheses.

### ISSUE THREAD

**Issue by russella** [marcodaniel/trad-biblatex#19]
Dear Marco, I'm not sure if you originally set out to emulate the behavior of the @techreport entry type. The current layout is almost correct, except that the "number" field should not be in parentheses.

Specifically, consider the entry:

@techreport{BKM95,
author={Julien Basch and Sanjeev Khanna and Rajeev Motwani},
title={On Diameter Verification and {B}oolean Matrix Multiplication},
number={STAN-CS-95-1544},
institution = {Department of Computer Science, Stanford University},
year={1995}
}

Then plain/bibtex produces the output
![bibtex-techreport](https://f.cloud.github.com/assets/2408045/971498/ace86e24-05e8-11e3-8d2c-ea7aa1442c44.png)
whereas biblatex/trad-plain produces the output
![biblatex-techreport](https://f.cloud.github.com/assets/2408045/971507/b93224e0-05e8-11e3-9ab3-81ffd24dcc9c.png)

**Comment by marcodaniel** [comment]
The issue depends on my fault. I forgot to define a new bibliography driver for "report" and some other minor changes.

The parens can be remove by
````
\DeclareFieldFormat[techreport]{number}{#1}
`````

The comma-issue is fixed.
