### ISSUE TITLE
@misc entry layout

### ISSUE THREAD

**Issue by russella** [marcodaniel/trad-biblatex#20]
Dear Marco, I am not sure if you originally set out to emulate the layout of the @misc entry type. There are some slight differences between trad-plain and plain. Specifically, consider the entry

@misc{Avrim,
author={Avrim Blum},
note={Personal communication},
year=2009,
}

Then bibtex/plain lays this out as follows:
![bibtex-misc](https://f.cloud.github.com/assets/2408045/971551/68f73f3c-05e9-11e3-8a6b-3e5c4a3d1c09.png)
whereas biblatex/trad-plain produces the following layout
![biblatex-misc](https://f.cloud.github.com/assets/2408045/971548/57423454-05e9-11e3-80f2-edafc4c20999.png)

(By the way, I prefer the way that trad-plain does it right now.)

**Comment by marcodaniel** [comment]
Added a new driver to modify the output. Is fixed now.
